spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillswap
    username: postgres
    password: 11206117001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: 8080

app:
  jwt:
    secret: "skillswap-super-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm"
    expiration-ms: 86400000   # 24 hours

logging:
  level:
    com.skillswap: DEBUG
    org.springframework.security: INFO
